name: Executar Terraform

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.1.4
  TF_CLI_ARGS: "-no-color"
  

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          create_credentials_file: true

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Validar Terraform
        run: terraform init
        working-directory: gce

      - name: Planejar Terraform
         
        run: |
          cp -a /home/runner/work/terraform/terraform/* . 
          terraform plan ${{ env.TF_CLI_ARGS }}
        working-directory: gce

      - name: Aplicar Terraform
        run: terraform apply tfplan ${{ env.TF_CLI_ARGS }}
        working-directory: gce
