name: Executar Terraform

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.1.4
  TF_CLI_ARGS: "-no-color"
  

jobs: 
  build-and-deploy-instances-in-GCP:
    runs-on: ubuntu-latest
    
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          create_credentials_file: true

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Validar Terraform
        run: terraform init
        working-directory: gce

      - name: Planejar Terraform
         
        run: |
          cp -a /home/runner/work/terraform/terraform/*.json .
          terraform plan -out tfplan ${{ env.TF_CLI_ARGS }}
        working-directory: gce

      - name: Aplicar Terraform
        run: terraform apply tfplan ${{ env.TF_CLI_ARGS }}
        working-directory: gce
        continue-on-error: true
  

  ansible:
    env: 
      working-directory: "/home/Ansible"
    runs-on: ubuntu-latest
    steps: 
  
      - name: Checkout other repo
        uses: actions/checkout@v3
        with:
          repository: pedrohedro/Ansible
          ref: main
      - name: Install Ansible
        run: |
          ls -a
          sudo apt-get update && sudo apt-get install -y ansible
          
          
